<?php

namespace Masca\PersonnelBundle\Repository;

/**
 * AbsenceEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
