<?php

namespace Masca\PersonnelBundle\Repository;

/**
 * AvanceSalaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvanceSalaireRepository extends \Doctrine\ORM\EntityRepository
{
}
