<?php

namespace Masca\PersonnelBundle\Repository;

/**
 * InfoSalaireFixeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoSalaireFixeRepository extends \Doctrine\ORM\EntityRepository
{
}
