<?php

namespace Masca\PersonnelBundle\Repository;

/**
 * InfoVolumeHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoVolumeHoraireRepository extends \Doctrine\ORM\EntityRepository
{
}
