<?php

namespace Masca\PersonnelBundle\Repository;

/**
 * MatiereLyceeEnseignerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereLyceeEnseignerRepository extends \Doctrine\ORM\EntityRepository
{
}
