<?php

namespace Masca\PersonnelBundle\Repository;

/**
 * MatiereUnivEnseignerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereUnivEnseignerRepository extends \Doctrine\ORM\EntityRepository
{
}
