<?php

namespace Masca\PersonnelBundle\Repository;
use Masca\PersonnelBundle\Entity\Employer;

/**
 * PointageEnseignantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointageEnseignantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPointageBy($mois, $annee, Employer $employer) {
        $query = $this->createQueryBuilder('pointage')
            ->where('pointage.employer = :employer')->setParameter('employer', $employer)
            ->andWhere('pointage.mois = :mois')->setParameter('mois', $mois)
            ->andWhere('pointage.annee = :annee')->setParameter('annee', $annee);
        return $query->getQuery()->getResult();
    }
}
