<?php

namespace Masca\PersonnelBundle\Repository;

/**
 * PointageEnseignantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointageEnseignantRepository extends \Doctrine\ORM\EntityRepository
{
}
