<?php

namespace Masca\PersonnelBundle\Repository;
use Masca\PersonnelBundle\Entity\Employer;

/**
 * SalaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function salaireNotValid(Employer $employer, $mois, $annee) {
        $query = $this->createQueryBuilder('salaire')
            ->where('salaire.employer = :employer')->setParameter('employer',$employer)
            ->andWhere('salaire.mois = :mois')->setParameter('mois', $mois)
            ->andWhere('salaire.annee = :annee')->setParameter('annee', $annee)
            ->getQuery();
        return $query->getOneOrNullResult() != null;
    }
}
