<?php

namespace Masca\PersonnelBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends \Doctrine\ORM\EntityRepository
{
}
