masca_personnel:
    resource: "@MascaPersonnelBundle/Resources/config/routing.yml"
    prefix:   /presonnel

oc_user:
    resource: "@OCUserBundle/Resources/config/routing.yml"
    prefix:   /

masca_etudiant:
    resource: "@MascaEtudiantBundle/Resources/config/routing.yml"
    prefix:   /etudiant

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
