<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * AbsenceLyceenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceLyceenRepository extends \Doctrine\ORM\EntityRepository
{
}
