<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * AbsenceUnivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceUnivRepository extends \Doctrine\ORM\EntityRepository
{
}
