<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * DatePayementEcolageLyceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatePayementEcolageLyceeRepository extends \Doctrine\ORM\EntityRepository
{
}
