<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * DatePayementEcolageUnivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatePayementEcolageUnivRepository extends \Doctrine\ORM\EntityRepository
{
}
