<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * EmploiDuTempsUnivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiDuTempsUnivRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMatiereBy($filiereParNiveau, $jourIndex, $heureIndex) {
        $query = $this->createQueryBuilder('emploiDuTemps')
            ->where('emploiDuTemps.filiereParNiveau = :filiereParNiveau')->setParameter('filiereParNiveau', $filiereParNiveau)
            ->andWhere('emploiDuTemps.jourIndex = :jourindex')->setParameter('jourindex',$jourIndex)
            ->andWhere('emploiDuTemps.heureIndex = :heureindex')->setParameter('heureindex',$heureIndex);
        return $query->getQuery()->getOneOrNullResult();
    }
}
