<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * FiliereParNiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliereParNiveauRepository extends \Doctrine\ORM\EntityRepository
{
}
