<?php

namespace Masca\EtudiantBundle\Repository;
use Masca\EtudiantBundle\Entity\Universitaire;
use Masca\EtudiantBundle\Entity\UniversitaireSonFiliere;

/**
 * FraisScolariteUnivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisScolariteUnivRepository extends \Doctrine\ORM\EntityRepository
{
    public function statusEcolage(Universitaire $universitaire) {
        $query = $this->createQueryBuilder('ecolage')
            ->leftJoin('ecolage.univSonFiliere','univSonFiliere')
            ->leftJoin('univSonFiliere.universitaire','universitaire')
            ->where('universitaire = :universitaire')->setParameter('universitaire',$universitaire)
            ->andWhere('ecolage.status = :status')->setParameter('status', 0)
            ->getQuery();
        return $query->getOneOrNullResult() != null;
    }
}
