<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * FraisScolariteUnivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisScolariteUnivRepository extends \Doctrine\ORM\EntityRepository
{
}
