<?php

namespace Masca\EtudiantBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MatiereLyceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereLyceeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMatieres($nbParPage, $page) {
        if($page < 1) {
            throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur: "'.$page.'").');
        }

        $query = $this->createQueryBuilder('matiere')
            ->orderBy('matiere.intitule', 'DESC')
            ->getQuery();

        $query->setFirstResult(($page-1) * $nbParPage)->setMaxResults($nbParPage);
        return new Paginator($query);
    }
}
