<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * MatierParUeFiliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatierParUeFiliereRepository extends \Doctrine\ORM\EntityRepository
{
}
