<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * NoteUnivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteUnivRepository extends \Doctrine\ORM\EntityRepository
{
}
