<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * RetardUnivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetardUnivRepository extends \Doctrine\ORM\EntityRepository
{
}
