<?php

namespace Masca\EtudiantBundle\Repository;

/**
 * RetardLyceenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetardLyceenRepository extends \Doctrine\ORM\EntityRepository
{
}
