<?php

namespace Masca\TresorBundle\Repository;

/**
 * MvmtLyceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MvmtLyceeRepository extends \Doctrine\ORM\EntityRepository
{
}
