<?php

namespace Masca\TresorBundle\Repository;

/**
 * SoldeUniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldeUniversiteRepository extends \Doctrine\ORM\EntityRepository
{
}
