<?php

namespace Masca\TresorBundle\Repository;

/**
 * SoldeLyceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldeLyceeRepository extends \Doctrine\ORM\EntityRepository
{
}
