parameters:
#    masca_etudiant.example.class: Masca\EtudiantBundle\Example

services:
#    masca_etudiant.example:
#        class: %masca_etudiant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
