<?php

namespace Masca\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EmploiDuTempsLyceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiDuTempsLyceeRepository extends EntityRepository
{
    public function getMatiereBy($classe, $jourIndex, $heureIndex) {
        $query = $this->createQueryBuilder('emploiDuTemps')
            ->where('emploiDuTemps.classe = :classe')->setParameter('classe', $classe)
            ->andWhere('emploiDuTemps.jourIndex = :jourindex')->setParameter('jourindex',$jourIndex)
            ->andWhere('emploiDuTemps.heureIndex = :heureindex')->setParameter('heureindex',$heureIndex);
        return $query->getQuery()->getOneOrNullResult();
    }
}
