<?php

namespace Masca\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FraisScolariteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisScolariteLyceenRepository extends EntityRepository
{
}
