<?php

namespace Masca\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrilleFraisScolariteUniversiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrilleFraisScolariteUniversiteRepository extends EntityRepository
{
    public function isValid(Filiere $filiere, NiveauEtude $niveauEtude) {
        $query = $this->createQueryBuilder('grille')
            ->where('grille.filiere = :filiere')->setParameter('filiere',$filiere)
            ->andWhere('grille.niveauEtude = :niveau')->setParameter('niveau', $niveauEtude);
        return $query->getQuery()->getOneOrNullResult() == null;
    }
}
