<?php

namespace Masca\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfoEtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoEtudiantRepository extends EntityRepository
{
}
