<?php

namespace Masca\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LyceenNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LyceenNoteRepository extends EntityRepository
{
    public function isValid(Lyceen $l, MatiereLycee $m) {
        $query = $this->createQueryBuilder('note')
            ->where('note.lyceen = :lyceen')->setParameter('lyceen',$l)
            ->andWhere('note.matiere = :matiere')->setParameter('matiere',$m);
        return $query->getQuery()->getOneOrNullResult() == null;
    }
}
