<?php

namespace Masca\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function statusEcolage(Lyceen $lyceen) {
        $query = $this->createQueryBuilder('ecolage')
            ->where('ecolage.lyceen = :lyceen')->setParameter('lyceen',$lyceen)
            ->andWhere('ecolage.status = :status')->setParameter('status', 0)
            ->getQuery();
        return $query->getOneOrNullResult() != null;
    }

    public function doublantMatricule(Person $person) {
        $query = $this->createQueryBuilder('person')
            ->where('person.numMatricule = :matricule')->setParameter('matricule',$person->getNumMatricule())
            ->getQuery();
        return $query->getOneOrNullResult() != null;
    }
}
